"""Hardcoded XBRL element -> line_item mapping for SEBI results filings.

Research decision, not config (CLAUDE.md Code conventions): an element absent
from LINE_ITEMS is quarantined as `unmapped_element`, never guessed, and
review of the quarantine grows this table under a new RULE_VERSION.

Line items keep each element's own meaning: the snake_case of its name
(typos included, e.g. "itmes"), per taxonomy namespace. Nothing here says that
a bank's `interest_earned` and a company's `revenue_from_operations` are the
same thing; canonical metrics across families are computed later, in
core/compute, from these faithful facts.

The expected unit of each element is part of the mapping: a fact reported in
another unit is quarantined as `unexpected_unit`.

Table first generated from the contract fixtures in tests/fixtures/nse_xbrl
(non-dimensional numeric facts only).
"""

from dataclasses import dataclass

from core.db.models import XbrlTaxonomy

RULE_VERSION = "nse-xbrl-1"

NS_FIN_2020 = "http://www.bseindia.com/xbrl/fin/2020-03-31/in-bse-fin"
NS_FIN_BANK_2019 = "http://www.bseindia.com/xbrl/fin/2019-09-30/in-bse-fin"
NS_CAPMKT_2020 = "http://www.bseindia.com/xbrl/2020-03-31/in-capmkt"


@dataclass(frozen=True)
class Taxonomy:
    family: XbrlTaxonomy
    schema_ref: str  # basename of link:schemaRef/@xlink:href
    entry_namespace: str  # declared in the instance; separates life from general insurance
    namespace: str  # namespace of the reported elements
    prefix: str  # stable prefix for financial_facts.xbrl_element; file prefixes are arbitrary


TAXONOMIES: tuple[Taxonomy, ...] = (
    Taxonomy(
        XbrlTaxonomy.IND_AS,
        "Ind-AS_entry_point_2020-03-31.xsd",
        "http://www.bseindia.com/xbrl/fin/2020-03-31/in-bse-fin/in-bse-fin-ent",
        NS_FIN_2020,
        "in-bse-fin-2020",
    ),
    Taxonomy(
        XbrlTaxonomy.NBFC,
        "in-bse-fin-2020-03-31.xsd",
        "http://www.bseindia.com/xbrl/fin/2020-03-31/in-bse-fin/in-bse-fin-ent",
        NS_FIN_2020,
        "in-bse-fin-2020",
    ),
    Taxonomy(
        XbrlTaxonomy.BANK,
        "banking_entry_point_2019-09-30.xsd",
        "http://www.bseindia.com/xbrl/fin/2019-09-30/in-bse-fin/in-bse-fin-ent",
        NS_FIN_BANK_2019,
        "in-bse-fin-bank-2019",
    ),
    Taxonomy(
        XbrlTaxonomy.LIFE_INSURANCE,
        "in-capmkt-ent-2020-03-31.xsd",
        "http://www.bseindia.com/xbrl/Insurance/2020-03-31/in-capmkt/in-capmkt-ent",
        NS_CAPMKT_2020,
        "in-capmkt-2020",
    ),
    Taxonomy(
        XbrlTaxonomy.GENERAL_INSURANCE,
        "in-capmkt-ent-2020-03-31.xsd",
        "http://www.bseindia.com/xbrl/GeneralInsurance/2020-03-31/in-capmkt/in-capmkt-ent",
        NS_CAPMKT_2020,
        "in-capmkt-2020",
    ),
)

# Filing metadata, read from the non-dimensional contexts; never stored as facts.
META_START = "DateOfStartOfReportingPeriod"
META_END = "DateOfEndOfReportingPeriod"
META_NATURE = "NatureOfReportStandaloneConsolidated"
META_QUARTER = "ReportingQuarter"
META_BOARD_MEETING = "DateOfBoardMeetingWhenFinancialResultsWereApproved"
META_CURRENCY = "DescriptionOfPresentationCurrency"
META_SYMBOLS = ("Symbol", "NSESymbol")
META_ISIN = "ISIN"
META_SCRIP_CODE = "ScripCode"

NATURE = {"standalone": "standalone", "consolidated": "consolidated"}

# Units as resolved from xbrli:unit measures (namespace URI, local name).
ISO4217 = "http://www.xbrl.org/2003/iso4217"
XBRLI = "http://www.xbrl.org/2003/instance"
UNITS: dict[tuple[tuple[tuple[str, str], ...], tuple[tuple[str, str], ...]], str] = {
    (((ISO4217, "INR"),), ()): "INR",
    (((ISO4217, "INR"),), ((XBRLI, "shares"),)): "INR/share",
    (((XBRLI, "pure"),), ()): "pure",
    (((XBRLI, "shares"),), ()): "shares",
}

# element local name -> (line_item, expected unit), per element namespace
LINE_ITEMS: dict[str, dict[str, tuple[str, str]]] = {
    NS_FIN_2020: {
        "AdjustmentsForDecreaseIncreaseInInventories": ("adjustments_for_decrease_increase_in_inventories", "INR"),
        "AdjustmentsForDecreaseIncreaseInOtherCurrentAssets": ("adjustments_for_decrease_increase_in_other_current_assets", "INR"),
        "AdjustmentsForDecreaseIncreaseInOtherNoncurrentAssets": ("adjustments_for_decrease_increase_in_other_noncurrent_assets", "INR"),
        "AdjustmentsForDecreaseIncreaseInTradeReceivablesCurrent": ("adjustments_for_decrease_increase_in_trade_receivables_current", "INR"),
        "AdjustmentsForDecreaseIncreaseInTradeReceivablesNoncurrent": ("adjustments_for_decrease_increase_in_trade_receivables_noncurrent", "INR"),
        "AdjustmentsForDepreciationAndAmortisationExpense": ("adjustments_for_depreciation_and_amortisation_expense", "INR"),
        "AdjustmentsForDividendIncome": ("adjustments_for_dividend_income", "INR"),
        "AdjustmentsForFairValueGainsLosses": ("adjustments_for_fair_value_gains_losses", "INR"),
        "AdjustmentsForFinanceCosts": ("adjustments_for_finance_costs", "INR"),
        "AdjustmentsForImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLoss": ("adjustments_for_impairment_loss_reversal_of_impairment_loss_recognised_in_profit_or_loss", "INR"),
        "AdjustmentsForIncreaseDecreaseInOtherCurrentLiabilities": ("adjustments_for_increase_decrease_in_other_current_liabilities", "INR"),
        "AdjustmentsForIncreaseDecreaseInOtherNoncurrentLiabilities": ("adjustments_for_increase_decrease_in_other_noncurrent_liabilities", "INR"),
        "AdjustmentsForIncreaseDecreaseInTradePayablesCurrent": ("adjustments_for_increase_decrease_in_trade_payables_current", "INR"),
        "AdjustmentsForIncreaseDecreaseInTradePayablesNoncurrent": ("adjustments_for_increase_decrease_in_trade_payables_noncurrent", "INR"),
        "AdjustmentsForInterestIncome": ("adjustments_for_interest_income", "INR"),
        "AdjustmentsForOtherBankBalances": ("adjustments_for_other_bank_balances", "INR"),
        "AdjustmentsForOtherFinancialAssetsCurrent": ("adjustments_for_other_financial_assets_current", "INR"),
        "AdjustmentsForOtherFinancialAssetsNoncurrent": ("adjustments_for_other_financial_assets_noncurrent", "INR"),
        "AdjustmentsForOtherFinancialLiabilitiesCurrent": ("adjustments_for_other_financial_liabilities_current", "INR"),
        "AdjustmentsForOtherFinancialLiabilitiesNoncurrent": ("adjustments_for_other_financial_liabilities_noncurrent", "INR"),
        "AdjustmentsForProvisionsCurrent": ("adjustments_for_provisions_current", "INR"),
        "AdjustmentsForProvisionsNoncurrent": ("adjustments_for_provisions_noncurrent", "INR"),
        "AdjustmentsForReconcileProfitLoss": ("adjustments_for_reconcile_profit_loss", "INR"),
        "AdjustmentsForSharebasedPayments": ("adjustments_for_sharebased_payments", "INR"),
        "AdjustmentsForUndistributedProfitsOfAssociates": ("adjustments_for_undistributed_profits_of_associates", "INR"),
        "AdjustmentsForUnrealisedForeignExchangeLossesGains": ("adjustments_for_unrealised_foreign_exchange_losses_gains", "INR"),
        "AmountOfItemThatWillBeReclassifiedToProfitAndLoss": ("amount_of_item_that_will_be_reclassified_to_profit_and_loss", "INR"),
        "AmountOfItemThatWillNotBeReclassifiedToProfitAndLoss": ("amount_of_item_that_will_not_be_reclassified_to_profit_and_loss", "INR"),
        "Assets": ("assets", "INR"),
        "BankBalanceOtherThanCashAndCashEquivalents": ("bank_balance_other_than_cash_and_cash_equivalents", "INR"),
        "BasicEarningsLossPerShareFromContinuingAndDiscontinuedOperations": ("basic_earnings_loss_per_share_from_continuing_and_discontinued_operations", "INR/share"),
        "BasicEarningsLossPerShareFromContinuingOperations": ("basic_earnings_loss_per_share_from_continuing_operations", "INR/share"),
        "BasicEarningsLossPerShareFromDiscontinuedOperations": ("basic_earnings_loss_per_share_from_discontinued_operations", "INR/share"),
        "BiologicalAssetsOtherThanBearerPlants": ("biological_assets_other_than_bearer_plants", "INR"),
        "Borrowings": ("borrowings", "INR"),
        "BorrowingsCurrent": ("borrowings_current", "INR"),
        "BorrowingsNoncurrent": ("borrowings_noncurrent", "INR"),
        "CapitalWorkInProgress": ("capital_work_in_progress", "INR"),
        "CashAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": ("cash_advances_and_loans_made_to_other_parties_classified_as_investing_activities", "INR"),
        "CashAndCashEquivalents": ("cash_and_cash_equivalents", "INR"),
        "CashAndCashEquivalentsCashFlowStatement": ("cash_and_cash_equivalents_cash_flow_statement", "INR"),
        "CashFlowsFromLosingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": ("cash_flows_from_losing_control_of_subsidiaries_or_other_businesses_classified_as_investing_activities", "INR"),
        "CashFlowsFromUsedInFinancingActivities": ("cash_flows_from_used_in_financing_activities", "INR"),
        "CashFlowsFromUsedInInvestingActivities": ("cash_flows_from_used_in_investing_activities", "INR"),
        "CashFlowsFromUsedInOperatingActivities": ("cash_flows_from_used_in_operating_activities", "INR"),
        "CashFlowsFromUsedInOperations": ("cash_flows_from_used_in_operations", "INR"),
        "CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": ("cash_flows_used_in_obtaining_control_of_subsidiaries_or_other_businesses_classified_as_investing_activities", "INR"),
        "CashPaymentForInvestmentInPartnershipFirmOrAssociationOfPersonsOrLimitedLiabilityPartnerships": ("cash_payment_for_investment_in_partnership_firm_or_association_of_persons_or_limited_liability_partnerships", "INR"),
        "CashPaymentsForFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": ("cash_payments_for_future_contracts_forward_contracts_option_contracts_and_swap_contracts_classified_as_investing_activities", "INR"),
        "CashReceiptsFromFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": ("cash_receipts_from_future_contracts_forward_contracts_option_contracts_and_swap_contracts_classified_as_investing_activities", "INR"),
        "CashReceiptsFromRepaymentOfAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": ("cash_receipts_from_repayment_of_advances_and_loans_made_to_other_parties_classified_as_investing_activities", "INR"),
        "CashReceiptsFromShareOfProfitsOfPartnershipFirmOrAssociationOfPersonsOrLimitedLiabilityPartnerships": ("cash_receipts_from_share_of_profits_of_partnership_firm_or_association_of_persons_or_limited_liability_partnerships", "INR"),
        "ChangesInInventoriesOfFinishedGoodsWorkInProgressAndStockInTrade": ("changes_in_inventories_of_finished_goods_work_in_progress_and_stock_in_trade", "INR"),
        "ComprehensiveIncomeForThePeriod": ("comprehensive_income_for_the_period", "INR"),
        "ComprehensiveIncomeForThePeriodAttributableToOwnersOfParent": ("comprehensive_income_for_the_period_attributable_to_owners_of_parent", "INR"),
        "ComprehensiveIncomeForThePeriodAttributableToOwnersOfParentNonControllingInterests": ("comprehensive_income_for_the_period_attributable_to_owners_of_parent_non_controlling_interests", "INR"),
        "CostOfMaterialsConsumed": ("cost_of_materials_consumed", "INR"),
        "CurrentAssets": ("current_assets", "INR"),
        "CurrentFinancialAssets": ("current_financial_assets", "INR"),
        "CurrentFinancialLiabilities": ("current_financial_liabilities", "INR"),
        "CurrentInvestments": ("current_investments", "INR"),
        "CurrentLiabilities": ("current_liabilities", "INR"),
        "CurrentTax": ("current_tax", "INR"),
        "CurrentTaxAssets": ("current_tax_assets", "INR"),
        "CurrentTaxAssetsNet": ("current_tax_assets_net", "INR"),
        "CurrentTaxLiabilities": ("current_tax_liabilities", "INR"),
        "DebtEquityRatio": ("debt_equity_ratio", "pure"),
        "DebtSecurities": ("debt_securities", "INR"),
        "DebtServiceCoverageRatio": ("debt_service_coverage_ratio", "pure"),
        "DeferredGovernmentGrantsCurrent": ("deferred_government_grants_current", "INR"),
        "DeferredGovernmentGrantsNoncurrent": ("deferred_government_grants_noncurrent", "INR"),
        "DeferredTax": ("deferred_tax", "INR"),
        "DeferredTaxAssetsNet": ("deferred_tax_assets_net", "INR"),
        "DeferredTaxLiabilitiesNet": ("deferred_tax_liabilities_net", "INR"),
        "Deposits": ("deposits", "INR"),
        "DepreciationDepletionAndAmortisationExpense": ("depreciation_depletion_and_amortisation_expense", "INR"),
        "DerivativeFinancialInstrumentsFinancialAssets": ("derivative_financial_instruments_financial_assets", "INR"),
        "DerivativeFinancialInstrumentsFinancialLiabilities": ("derivative_financial_instruments_financial_liabilities", "INR"),
        "DilutedEarningsLossPerShareFromContinuingAndDiscontinuedOperations": ("diluted_earnings_loss_per_share_from_continuing_and_discontinued_operations", "INR/share"),
        "DilutedEarningsLossPerShareFromContinuingOperations": ("diluted_earnings_loss_per_share_from_continuing_operations", "INR/share"),
        "DilutedEarningsLossPerShareFromDiscontinuedOperations": ("diluted_earnings_loss_per_share_from_discontinued_operations", "INR/share"),
        "DividendIncome": ("dividend_income", "INR"),
        "DividendsPaidClassifiedAsFinancingActivities": ("dividends_paid_classified_as_financing_activities", "INR"),
        "DividendsReceivedClassifiedAsInvestingActivities": ("dividends_received_classified_as_investing_activities", "INR"),
        "DividendsReceivedClassifiedAsOperatingActivities": ("dividends_received_classified_as_operating_activities", "INR"),
        "EffectOfExchangeRateChangesOnCashAndCashEquivalents": ("effect_of_exchange_rate_changes_on_cash_and_cash_equivalents", "INR"),
        "EmployeeBenefitExpense": ("employee_benefit_expense", "INR"),
        "Equity": ("equity", "INR"),
        "EquityAndLiabilities": ("equity_and_liabilities", "INR"),
        "EquityAttributableToOwnersOfParent": ("equity_attributable_to_owners_of_parent", "INR"),
        "EquityShareCapital": ("equity_share_capital", "INR"),
        "ExceptionalItemsBeforeTax": ("exceptional_items_before_tax", "INR"),
        "Expenses": ("expenses", "INR"),
        "FaceValueOfEquityShareCapital": ("face_value_of_equity_share_capital", "INR/share"),
        "FeesAndCommissionExpense": ("fees_and_commission_expense", "INR"),
        "FeesAndCommissionIncome": ("fees_and_commission_income", "INR"),
        "FinanceCosts": ("finance_costs", "INR"),
        "FinancialLiabilities": ("financial_liabilities", "INR"),
        "FinanicalAssets": ("finanical_assets", "INR"),
        "Goodwill": ("goodwill", "INR"),
        "ImpairmentOnFinancialInstruments": ("impairment_on_financial_instruments", "INR"),
        "Income": ("income", "INR"),
        "IncomeTaxRelatingToItmesThatWillBeReclassifiedToProfitOrLoss": ("income_tax_relating_to_itmes_that_will_be_reclassified_to_profit_or_loss", "INR"),
        "IncomeTaxRelatingToItmesThatWillNotBeReclassifiedToProfitOrLoss": ("income_tax_relating_to_itmes_that_will_not_be_reclassified_to_profit_or_loss", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsFinancingActivities": ("income_taxes_paid_refund_classified_as_financing_activities", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsInvestingActivities": ("income_taxes_paid_refund_classified_as_investing_activities", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsOperatingActivities": ("income_taxes_paid_refund_classified_as_operating_activities", "INR"),
        "IncreaseDecreaseInCashAndCashEquivalents": ("increase_decrease_in_cash_and_cash_equivalents", "INR"),
        "IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges": ("increase_decrease_in_cash_and_cash_equivalents_before_effect_of_exchange_rate_changes", "INR"),
        "IntangibleAssetsUnderDevelopment": ("intangible_assets_under_development", "INR"),
        "InterestEarned": ("interest_earned", "INR"),
        "InterestPaidClassifiedAsFinancingActivities": ("interest_paid_classified_as_financing_activities", "INR"),
        "InterestPaidClassifiedAsOperatingActivities": ("interest_paid_classified_as_operating_activities", "INR"),
        "InterestReceivedClassifiedAsInvestingActivities": ("interest_received_classified_as_investing_activities", "INR"),
        "InterestReceivedClassifiedAsOperatingActivities": ("interest_received_classified_as_operating_activities", "INR"),
        "InterestServiceCoverageRatio": ("interest_service_coverage_ratio", "pure"),
        "Inventories": ("inventories", "INR"),
        "InvestmentProperty": ("investment_property", "INR"),
        "Investments": ("investments", "INR"),
        "InvestmentsAccountedForUsingEquityMethod": ("investments_accounted_for_using_equity_method", "INR"),
        "Liabilities": ("liabilities", "INR"),
        "LiabilitiesDirectlyAssociatedWithAssetsInDisposalGroupClassifiedAsHeldForSale": ("liabilities_directly_associated_with_assets_in_disposal_group_classified_as_held_for_sale", "INR"),
        "Loans": ("loans", "INR"),
        "LoansCurrent": ("loans_current", "INR"),
        "LoansNoncurrent": ("loans_noncurrent", "INR"),
        "NetGainOnDerecognitionOfFinancialInstrumentsUnderAmortisedCostCategory": ("net_gain_on_derecognition_of_financial_instruments_under_amortised_cost_category", "INR"),
        "NetGainOnFairValueChanges": ("net_gain_on_fair_value_changes", "INR"),
        "NetLossOnDerecognitionOfFinancialInstrumentsUnderAmortisedCostCategory": ("net_loss_on_derecognition_of_financial_instruments_under_amortised_cost_category", "INR"),
        "NetLossOnFairValueChanges": ("net_loss_on_fair_value_changes", "INR"),
        "NetMovementInRegulatoryDeferralAccountBalancesRelatedToProfitOrLossAndTheRelatedDeferredTaxMovement": ("net_movement_in_regulatory_deferral_account_balances_related_to_profit_or_loss_and_the_related_deferred_tax_movement", "INR"),
        "NetSegmentAssets": ("net_segment_assets", "INR"),
        "NetSegmentLiabilities": ("net_segment_liabilities", "INR"),
        "NonControllingInterest": ("non_controlling_interest", "INR"),
        "NonFinancialAssets": ("non_financial_assets", "INR"),
        "NonFinancialLiabilities": ("non_financial_liabilities", "INR"),
        "NoncurrentAssets": ("noncurrent_assets", "INR"),
        "NoncurrentAssetsClassifiedAsHeldForSale": ("noncurrent_assets_classified_as_held_for_sale", "INR"),
        "NoncurrentFinancialAssets": ("noncurrent_financial_assets", "INR"),
        "NoncurrentFinancialLiabilities": ("noncurrent_financial_liabilities", "INR"),
        "NoncurrentInvestments": ("noncurrent_investments", "INR"),
        "NoncurrentLiabilities": ("noncurrent_liabilities", "INR"),
        "OtherAdjustmentsForNoncashItems": ("other_adjustments_for_noncash_items", "INR"),
        "OtherAdjustmentsForWhichCashEffectsAreInvestingOrFinancingCashFlow": ("other_adjustments_for_which_cash_effects_are_investing_or_financing_cash_flow", "INR"),
        "OtherAdjustmentsToReconcileProfitLoss": ("other_adjustments_to_reconcile_profit_loss", "INR"),
        "OtherCashPaymentsToAcquireEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": ("other_cash_payments_to_acquire_equity_or_debt_instruments_of_other_entities_classified_as_investing_activities", "INR"),
        "OtherCashPaymentsToAcquireInterestsInJointVenturesClassifiedAsInvestingActivities": ("other_cash_payments_to_acquire_interests_in_joint_ventures_classified_as_investing_activities", "INR"),
        "OtherCashReceiptsFromSalesOfEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": ("other_cash_receipts_from_sales_of_equity_or_debt_instruments_of_other_entities_classified_as_investing_activities", "INR"),
        "OtherCashReceiptsFromSalesOfInterestsInJointVenturesClassifiedAsInvestingActivities": ("other_cash_receipts_from_sales_of_interests_in_joint_ventures_classified_as_investing_activities", "INR"),
        "OtherComprehensiveIncome": ("other_comprehensive_income", "INR"),
        "OtherComprehensiveIncomeNetOfTaxes": ("other_comprehensive_income_net_of_taxes", "INR"),
        "OtherCurrentAssets": ("other_current_assets", "INR"),
        "OtherCurrentFinancialAssets": ("other_current_financial_assets", "INR"),
        "OtherCurrentFinancialLiabilities": ("other_current_financial_liabilities", "INR"),
        "OtherCurrentLiabilities": ("other_current_liabilities", "INR"),
        "OtherEquity": ("other_equity", "INR"),
        "OtherExpenses": ("other_expenses", "INR"),
        "OtherFinancialAssets": ("other_financial_assets", "INR"),
        "OtherFinancialLiabilities": ("other_financial_liabilities", "INR"),
        "OtherIncome": ("other_income", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsFinancingActivities": ("other_inflows_outflows_of_cash_classified_as_financing_activities", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsInvestingActivities": ("other_inflows_outflows_of_cash_classified_as_investing_activities", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsOperatingActivities": ("other_inflows_outflows_of_cash_classified_as_operating_activities", "INR"),
        "OtherIntangibleAssets": ("other_intangible_assets", "INR"),
        "OtherNonFinancialAssets": ("other_non_financial_assets", "INR"),
        "OtherNonFinancialLiabilities": ("other_non_financial_liabilities", "INR"),
        "OtherNoncurrentAssets": ("other_noncurrent_assets", "INR"),
        "OtherNoncurrentFinancialAssets": ("other_noncurrent_financial_assets", "INR"),
        "OtherNoncurrentFinancialLiabilities": ("other_noncurrent_financial_liabilities", "INR"),
        "OtherNoncurrentLiabilities": ("other_noncurrent_liabilities", "INR"),
        "OtherReceivables": ("other_receivables", "INR"),
        "OtherRevenueFromOperations": ("other_revenue_from_operations", "INR"),
        "OtherUnallocableExpenditureNetOffUnAllocableIncome": ("other_unallocable_expenditure_net_off_un_allocable_income", "INR"),
        "PaidUpValueOfEquityShareCapital": ("paid_up_value_of_equity_share_capital", "INR"),
        "PaymentsFromChangesInOwnershipInterestsInSubsidiaries": ("payments_from_changes_in_ownership_interests_in_subsidiaries", "INR"),
        "PaymentsOfFinanceLeaseLiabilitiesClassifiedAsFinancingActivities": ("payments_of_finance_lease_liabilities_classified_as_financing_activities", "INR"),
        "PaymentsOfLeaseLiabilitiesClassifiedAsFinancingActivities": ("payments_of_lease_liabilities_classified_as_financing_activities", "INR"),
        "PaymentsOfOtherEquityInstruments": ("payments_of_other_equity_instruments", "INR"),
        "PaymentsToAcquireOrRedeemEntitysShares": ("payments_to_acquire_or_redeem_entitys_shares", "INR"),
        "ProceedsFromBiologicalAssetsOtherThanBearerPlantsClassifiedAsInvestingActivities": ("proceeds_from_biological_assets_other_than_bearer_plants_classified_as_investing_activities", "INR"),
        "ProceedsFromBorrowingsClassifiedAsFinancingActivities": ("proceeds_from_borrowings_classified_as_financing_activities", "INR"),
        "ProceedsFromChangesInOwnershipInterestsInSubsidiaries": ("proceeds_from_changes_in_ownership_interests_in_subsidiaries", "INR"),
        "ProceedsFromExerciseOfStockOptions": ("proceeds_from_exercise_of_stock_options", "INR"),
        "ProceedsFromGovernmentGrantsClassifiedAsInvestingActivities": ("proceeds_from_government_grants_classified_as_investing_activities", "INR"),
        "ProceedsFromIssuingDebenturesNotesBondsEtc": ("proceeds_from_issuing_debentures_notes_bonds_etc", "INR"),
        "ProceedsFromIssuingOtherEquityInstruments": ("proceeds_from_issuing_other_equity_instruments", "INR"),
        "ProceedsFromIssuingSharesClassifiedAsFinancingActivities": ("proceeds_from_issuing_shares_classified_as_financing_activities", "INR"),
        "ProceedsFromSalesOfGoodwillClassifiedAsInvestingActivities": ("proceeds_from_sales_of_goodwill_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities": ("proceeds_from_sales_of_intangible_assets_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfIntangibleAssetsUnderDevelopment": ("proceeds_from_sales_of_intangible_assets_under_development", "INR"),
        "ProceedsFromSalesOfInvestmentPropertyClassifiedAsInvestingActivities": ("proceeds_from_sales_of_investment_property_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfOtherLongTermAssetsClassifiedAsInvestingActivities": ("proceeds_from_sales_of_other_long_term_assets_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities": ("proceeds_from_sales_of_property_plant_and_equipment_classified_as_investing_activities", "INR"),
        "ProfitBeforeExceptionalItemsAndTax": ("profit_before_exceptional_items_and_tax", "INR"),
        "ProfitBeforeTax": ("profit_before_tax", "INR"),
        "ProfitLossForPeriod": ("profit_loss_for_period", "INR"),
        "ProfitLossForPeriodFromContinuingOperations": ("profit_loss_for_period_from_continuing_operations", "INR"),
        "ProfitLossFromDiscontinuedOperationsAfterTax": ("profit_loss_from_discontinued_operations_after_tax", "INR"),
        "ProfitLossFromDiscontinuedOperationsBeforeTax": ("profit_loss_from_discontinued_operations_before_tax", "INR"),
        "ProfitOrLossAttributableToNonControllingInterests": ("profit_or_loss_attributable_to_non_controlling_interests", "INR"),
        "ProfitOrLossAttributableToOwnersOfParent": ("profit_or_loss_attributable_to_owners_of_parent", "INR"),
        "PropertyPlantAndEquipment": ("property_plant_and_equipment", "INR"),
        "Provisions": ("provisions", "INR"),
        "ProvisionsCurrent": ("provisions_current", "INR"),
        "ProvisionsNoncurrent": ("provisions_noncurrent", "INR"),
        "PurchaseOfBiologicalAssetsOtherThanBearerPlantsClassifiedAsInvestingActivities": ("purchase_of_biological_assets_other_than_bearer_plants_classified_as_investing_activities", "INR"),
        "PurchaseOfGoodwillClassifiedAsInvestingActivities": ("purchase_of_goodwill_classified_as_investing_activities", "INR"),
        "PurchaseOfIntangibleAssetsClassifiedAsInvestingActivities": ("purchase_of_intangible_assets_classified_as_investing_activities", "INR"),
        "PurchaseOfIntangibleAssetsUnderDevelopment": ("purchase_of_intangible_assets_under_development", "INR"),
        "PurchaseOfInvestmentPropertyClassifiedAsInvestingActivities": ("purchase_of_investment_property_classified_as_investing_activities", "INR"),
        "PurchaseOfOtherLongTermAssetsClassifiedAsInvestingActivities": ("purchase_of_other_long_term_assets_classified_as_investing_activities", "INR"),
        "PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities": ("purchase_of_property_plant_and_equipment_classified_as_investing_activities", "INR"),
        "PurchasesOfStockInTrade": ("purchases_of_stock_in_trade", "INR"),
        "RegulatoryDeferralAccountCreditBalancesAndRelatedDeferredTaxLiability": ("regulatory_deferral_account_credit_balances_and_related_deferred_tax_liability", "INR"),
        "RegulatoryDeferralAccountDebitBalancesAndRelatedDeferredTaxAssets": ("regulatory_deferral_account_debit_balances_and_related_deferred_tax_assets", "INR"),
        "RentalIncome": ("rental_income", "INR"),
        "RepaymentsOfBorrowingsClassifiedAsFinancingActivities": ("repayments_of_borrowings_classified_as_financing_activities", "INR"),
        "ReserveExcludingRevaluationReserves": ("reserve_excluding_revaluation_reserves", "INR"),
        "RevenueFromOperations": ("revenue_from_operations", "INR"),
        "RevenueFromSaleOfProduct": ("revenue_from_sale_of_product", "INR"),
        "RevenueFromSaleOfServices": ("revenue_from_sale_of_services", "INR"),
        "SegmentAssets": ("segment_assets", "INR"),
        "SegmentFinanceCosts": ("segment_finance_costs", "INR"),
        "SegmentLiabilities": ("segment_liabilities", "INR"),
        "SegmentProfitBeforeTax": ("segment_profit_before_tax", "INR"),
        "SegmentProfitLossBeforeTaxAndFinanceCosts": ("segment_profit_loss_before_tax_and_finance_costs", "INR"),
        "SegmentRevenue": ("segment_revenue", "INR"),
        "SegmentRevenueFromOperations": ("segment_revenue_from_operations", "INR"),
        "ShareOfProfitAndLossFromPartnershipFirmOrAssociationOfPersonsOrLimitedLiabilityPartnerships": ("share_of_profit_and_loss_from_partnership_firm_or_association_of_persons_or_limited_liability_partnerships", "INR"),
        "ShareOfProfitLossOfAssociatesAndJointVenturesAccountedForUsingEquityMethod": ("share_of_profit_loss_of_associates_and_joint_ventures_accounted_for_using_equity_method", "INR"),
        "SubordinatedLiabilities": ("subordinated_liabilities", "INR"),
        "TaxExpense": ("tax_expense", "INR"),
        "TaxExpenseOfDiscontinuedOperations": ("tax_expense_of_discontinued_operations", "INR"),
        "TotalOutstandingDuesOfCreditorsOtherThanMicroEnterpriseAndSmallEnterprise": ("total_outstanding_dues_of_creditors_other_than_micro_enterprise_and_small_enterprise", "INR"),
        "TotalOutstandingDuesOfMicroEnterpriseAndSmallEnterprise": ("total_outstanding_dues_of_micro_enterprise_and_small_enterprise", "INR"),
        "TotalOutstandingDuesOfMicroEnterpriseAndSmallEnterpriseOtherPayables": ("total_outstanding_dues_of_micro_enterprise_and_small_enterprise_other_payables", "INR"),
        "TradePayablesCurrent": ("trade_payables_current", "INR"),
        "TradePayablesNoncurrent": ("trade_payables_noncurrent", "INR"),
        "TradeReceivables": ("trade_receivables", "INR"),
        "TradeReceivablesCurrent": ("trade_receivables_current", "INR"),
        "TradeReceivablesNoncurrent": ("trade_receivables_noncurrent", "INR"),
        "UnAllocableAssets": ("un_allocable_assets", "INR"),
        "UnAllocableLiabilities": ("un_allocable_liabilities", "INR"),
    },
    NS_FIN_BANK_2019: {
        "AdditionalTier1Ratio": ("additional_tier_1_ratio", "pure"),
        "AdjustmentsForDecreaseIncreaseInInventories": ("adjustments_for_decrease_increase_in_inventories", "INR"),
        "AdjustmentsForDecreaseIncreaseInOtherCurrentAssets": ("adjustments_for_decrease_increase_in_other_current_assets", "INR"),
        "AdjustmentsForDecreaseIncreaseInTradeReceivables": ("adjustments_for_decrease_increase_in_trade_receivables", "INR"),
        "AdjustmentsForDepreciationAndAmortisationExpense": ("adjustments_for_depreciation_and_amortisation_expense", "INR"),
        "AdjustmentsForDividendIncome": ("adjustments_for_dividend_income", "INR"),
        "AdjustmentsForFinanceCosts": ("adjustments_for_finance_costs", "INR"),
        "AdjustmentsForImpairmentLossReversalOfImpairmentLossRecognisedInProfitOrLoss": ("adjustments_for_impairment_loss_reversal_of_impairment_loss_recognised_in_profit_or_loss", "INR"),
        "AdjustmentsForIncreaseDecreaseInOtherCurrentLiabilities": ("adjustments_for_increase_decrease_in_other_current_liabilities", "INR"),
        "AdjustmentsForIncreaseDecreaseInTradePayables": ("adjustments_for_increase_decrease_in_trade_payables", "INR"),
        "AdjustmentsForProvisions": ("adjustments_for_provisions", "INR"),
        "AdjustmentsForReconcileProfitLoss": ("adjustments_for_reconcile_profit_loss", "INR"),
        "AdjustmentsForSharebasedPayments": ("adjustments_for_sharebased_payments", "INR"),
        "AdjustmentsForUnrealisedForeignExchangeLossesGains": ("adjustments_for_unrealised_foreign_exchange_losses_gains", "INR"),
        "AdjustmentsForWorkingCapital": ("adjustments_for_working_capital", "INR"),
        "AdjustmentsToProfitLoss": ("adjustments_to_profit_loss", "INR"),
        "Advances": ("advances", "INR"),
        "BalancesWithBanksAndMoneyAtCallAndShortNotice": ("balances_with_banks_and_money_at_call_and_short_notice", "INR"),
        "BasicEarningsPerShareAfterExtraordinaryItems": ("basic_earnings_per_share_after_extraordinary_items", "INR/share"),
        "BasicEarningsPerShareBeforeExtraordinaryItems": ("basic_earnings_per_share_before_extraordinary_items", "INR/share"),
        "Borrowings": ("borrowings", "INR"),
        "CET1Ratio": ("cet1_ratio", "pure"),
        "Capital": ("capital", "INR"),
        "CapitalAndLiabilities": ("capital_and_liabilities", "INR"),
        "CashAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": ("cash_advances_and_loans_made_to_other_parties_classified_as_investing_activities", "INR"),
        "CashAndBalancesWithReserveBankOfIndia": ("cash_and_balances_with_reserve_bank_of_india", "INR"),
        "CashAndCashEquivalentsCashFlowStatement": ("cash_and_cash_equivalents_cash_flow_statement", "INR"),
        "CashFlowsFromLosingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": ("cash_flows_from_losing_control_of_subsidiaries_or_other_businesses_classified_as_investing_activities", "INR"),
        "CashFlowsFromUsedInFinancingActivities": ("cash_flows_from_used_in_financing_activities", "INR"),
        "CashFlowsFromUsedInFinancingActivitiesBeforeExtraordinaryItems": ("cash_flows_from_used_in_financing_activities_before_extraordinary_items", "INR"),
        "CashFlowsFromUsedInInvestingActivities": ("cash_flows_from_used_in_investing_activities", "INR"),
        "CashFlowsFromUsedInInvestingActivitiesBeforeExtraordinaryItems": ("cash_flows_from_used_in_investing_activities_before_extraordinary_items", "INR"),
        "CashFlowsFromUsedInOperatingActivities": ("cash_flows_from_used_in_operating_activities", "INR"),
        "CashFlowsFromUsedInOperatingActivitiesBeforeExtraordinaryItems": ("cash_flows_from_used_in_operating_activities_before_extraordinary_items", "INR"),
        "CashFlowsFromUsedInOperations": ("cash_flows_from_used_in_operations", "INR"),
        "CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": ("cash_flows_used_in_obtaining_control_of_subsidiaries_or_other_businesses_classified_as_investing_activities", "INR"),
        "CashPaymentForInvestmentInPartnershipFirmOrAssociationOfPersonsOrLimitedLiabilityPartnerships": ("cash_payment_for_investment_in_partnership_firm_or_association_of_persons_or_limited_liability_partnerships", "INR"),
        "CashPaymentsForFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": ("cash_payments_for_future_contracts_forward_contracts_option_contracts_and_swap_contracts_classified_as_investing_activities", "INR"),
        "CashReceiptsFromFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": ("cash_receipts_from_future_contracts_forward_contracts_option_contracts_and_swap_contracts_classified_as_investing_activities", "INR"),
        "CashReceiptsFromRepaymentOfAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": ("cash_receipts_from_repayment_of_advances_and_loans_made_to_other_parties_classified_as_investing_activities", "INR"),
        "CashReceiptsFromShareOfProfitsOfPartnershipFirmOrAssociationOfPersonsOrLimitedLiabilityPartnerships": ("cash_receipts_from_share_of_profits_of_partnership_firm_or_association_of_persons_or_limited_liability_partnerships", "INR"),
        "Deposits": ("deposits", "INR"),
        "DilutedEarningsPerShareAfterExtraordinaryItems": ("diluted_earnings_per_share_after_extraordinary_items", "INR/share"),
        "DilutedEarningsPerShareBeforeExtraordinaryItems": ("diluted_earnings_per_share_before_extraordinary_items", "INR/share"),
        "DividendsPaidClassifiedAsFinancingActivities": ("dividends_paid_classified_as_financing_activities", "INR"),
        "DividendsReceivedClassifiedAsInvestingActivities": ("dividends_received_classified_as_investing_activities", "INR"),
        "DividendsReceivedClassifiedAsOperatingActivities": ("dividends_received_classified_as_operating_activities", "INR"),
        "EffectOfExchangeRateChangesOnCashAndCashEquivalents": ("effect_of_exchange_rate_changes_on_cash_and_cash_equivalents", "INR"),
        "EmployeesCost": ("employees_cost", "INR"),
        "ExceptionalItems": ("exceptional_items", "INR"),
        "ExpenditureExcludingProvisionsAndContingencies": ("expenditure_excluding_provisions_and_contingencies", "INR"),
        "ExtraordinaryItems": ("extraordinary_items", "INR"),
        "FaceValueOfEquityShareCapital": ("face_value_of_equity_share_capital", "INR/share"),
        "FixedAssets": ("fixed_assets", "INR"),
        "GrossNonPerformingAssets": ("gross_non_performing_assets", "INR"),
        "Income": ("income", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsFinancingActivities": ("income_taxes_paid_refund_classified_as_financing_activities", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsInvestingActivities": ("income_taxes_paid_refund_classified_as_investing_activities", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsOperatingActivities": ("income_taxes_paid_refund_classified_as_operating_activities", "INR"),
        "IncreaseDecreaseInCashAndCashEquivalents": ("increase_decrease_in_cash_and_cash_equivalents", "INR"),
        "IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges": ("increase_decrease_in_cash_and_cash_equivalents_before_effect_of_exchange_rate_changes", "INR"),
        "InterSegmentRevenue": ("inter_segment_revenue", "INR"),
        "InterestEarned": ("interest_earned", "INR"),
        "InterestExpended": ("interest_expended", "INR"),
        "InterestOnBalancesWithReserveBankOfIndiaAndOtherInterBankFunds": ("interest_on_balances_with_reserve_bank_of_india_and_other_inter_bank_funds", "INR"),
        "InterestOrDiscountOnAdvancesOrBills": ("interest_or_discount_on_advances_or_bills", "INR"),
        "InterestPaidClassifiedAsFinancingActivities": ("interest_paid_classified_as_financing_activities", "INR"),
        "InterestPaidClassifiedAsOperatingActivities": ("interest_paid_classified_as_operating_activities", "INR"),
        "InterestReceivedClassifiedAsInvestingActivities": ("interest_received_classified_as_investing_activities", "INR"),
        "InterestReceivedClassifiedAsOperatingActivities": ("interest_received_classified_as_operating_activities", "INR"),
        "Investments": ("investments", "INR"),
        "NonPerformingAssets": ("non_performing_assets", "INR"),
        "OperatingExpenses": ("operating_expenses", "INR"),
        "OperatingProfitBeforeProvisionAndContingencies": ("operating_profit_before_provision_and_contingencies", "INR"),
        "OtherAdjustmentsForNoncashItems": ("other_adjustments_for_noncash_items", "INR"),
        "OtherAdjustmentsForWhichCashEffectsAreInvestingOrFinancingCashFlow": ("other_adjustments_for_which_cash_effects_are_investing_or_financing_cash_flow", "INR"),
        "OtherAdjustmentsToReconcileProfitLoss": ("other_adjustments_to_reconcile_profit_loss", "INR"),
        "OtherAssets": ("other_assets", "INR"),
        "OtherCashPaymentsToAcquireEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": ("other_cash_payments_to_acquire_equity_or_debt_instruments_of_other_entities_classified_as_investing_activities", "INR"),
        "OtherCashPaymentsToAcquireInterestsInJointVenturesClassifiedAsInvestingActivities": ("other_cash_payments_to_acquire_interests_in_joint_ventures_classified_as_investing_activities", "INR"),
        "OtherCashReceiptsFromSalesOfEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": ("other_cash_receipts_from_sales_of_equity_or_debt_instruments_of_other_entities_classified_as_investing_activities", "INR"),
        "OtherCashReceiptsFromSalesOfInterestsInJointVenturesClassifiedAsInvestingActivities": ("other_cash_receipts_from_sales_of_interests_in_joint_ventures_classified_as_investing_activities", "INR"),
        "OtherIncome": ("other_income", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsFinancingActivities": ("other_inflows_outflows_of_cash_classified_as_financing_activities", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsInvestingActivities": ("other_inflows_outflows_of_cash_classified_as_investing_activities", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsOperatingActivities": ("other_inflows_outflows_of_cash_classified_as_operating_activities", "INR"),
        "OtherInterest": ("other_interest", "INR"),
        "OtherLiabilitiesAndProvisions": ("other_liabilities_and_provisions", "INR"),
        "OtherOperatingExpenses": ("other_operating_expenses", "INR"),
        "OtherUnallocableExpenditureNetOffUnAllocableIncome": ("other_unallocable_expenditure_net_off_un_allocable_income", "INR"),
        "PaidUpValueOfEquityShareCapital": ("paid_up_value_of_equity_share_capital", "INR"),
        "PaymentForExtraordinaryItemsClassifiedAsFinancingActivities": ("payment_for_extraordinary_items_classified_as_financing_activities", "INR"),
        "PaymentForExtraordinaryItemsClassifiedAsInvestingActivities": ("payment_for_extraordinary_items_classified_as_investing_activities", "INR"),
        "PaymentForExtraordinaryItemsClassifiedAsOperatingActivities": ("payment_for_extraordinary_items_classified_as_operating_activities", "INR"),
        "PercentageOfGrossNpa": ("percentage_of_gross_npa", "pure"),
        "PercentageOfShareHeldByGovernmentOfIndia": ("percentage_of_share_held_by_government_of_india", "pure"),
        "ProceedsFromBorrowingsClassifiedAsFinancingActivities": ("proceeds_from_borrowings_classified_as_financing_activities", "INR"),
        "ProceedsFromExtraordinaryItemsClassifiedAsFinancingActivities": ("proceeds_from_extraordinary_items_classified_as_financing_activities", "INR"),
        "ProceedsFromExtraordinaryItemsClassifiedAsInvestingActivities": ("proceeds_from_extraordinary_items_classified_as_investing_activities", "INR"),
        "ProceedsFromExtraordinaryItemsClassifiedAsOperatingActivities": ("proceeds_from_extraordinary_items_classified_as_operating_activities", "INR"),
        "ProceedsFromGovernmentGrantsClassifiedAsInvestingActivities": ("proceeds_from_government_grants_classified_as_investing_activities", "INR"),
        "ProceedsFromIssuingDebenturesNotesBondsEtc": ("proceeds_from_issuing_debentures_notes_bonds_etc", "INR"),
        "ProceedsFromIssuingOtherEquityInstruments": ("proceeds_from_issuing_other_equity_instruments", "INR"),
        "ProceedsFromIssuingShares": ("proceeds_from_issuing_shares", "INR"),
        "ProceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities": ("proceeds_from_sales_of_intangible_assets_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfTangibleAssetsClassifiedAsInvestingActivities": ("proceeds_from_sales_of_tangible_assets_classified_as_investing_activities", "INR"),
        "ProfitLossAfterTaxesMinorityInterestAndShareOfProfitLossOfAssociates": ("profit_loss_after_taxes_minority_interest_and_share_of_profit_loss_of_associates", "INR"),
        "ProfitLossForThePeriod": ("profit_loss_for_the_period", "INR"),
        "ProfitLossFromOrdinaryActivitiesAfterTax": ("profit_loss_from_ordinary_activities_after_tax", "INR"),
        "ProfitLossFromOrdinaryActivitiesBeforeTax": ("profit_loss_from_ordinary_activities_before_tax", "INR"),
        "ProfitLossOfMinorityInterest": ("profit_loss_of_minority_interest", "INR"),
        "ProvisionsOtherThanTaxAndContingencies": ("provisions_other_than_tax_and_contingencies", "INR"),
        "PurchaseOfIntangibleAssetsClassifiedAsInvestingActivities": ("purchase_of_intangible_assets_classified_as_investing_activities", "INR"),
        "PurchaseOfTangibleAssetsClassifiedAsInvestingActivities": ("purchase_of_tangible_assets_classified_as_investing_activities", "INR"),
        "RepaymentsOfBorrowingsClassifiedAsFinancingActivities": ("repayments_of_borrowings_classified_as_financing_activities", "INR"),
        "ReservesAndSurplus": ("reserves_and_surplus", "INR"),
        "ReturnOnAssets": ("return_on_assets", "INR"),
        "RevenueOnInvestments": ("revenue_on_investments", "INR"),
        "SegmentAssets": ("segment_assets", "INR"),
        "SegmentFinanceCosts": ("segment_finance_costs", "INR"),
        "SegmentLiabilities": ("segment_liabilities", "INR"),
        "SegmentProfitLossBeforeTaxAndFinanceCosts": ("segment_profit_loss_before_tax_and_finance_costs", "INR"),
        "SegmentRevenue": ("segment_revenue", "INR"),
        "ShareOfProfitAndLossFromPartnershipFirmOrAssociationOfPersonsOrLimitedLiabilityPartnerships": ("share_of_profit_and_loss_from_partnership_firm_or_association_of_persons_or_limited_liability_partnerships", "INR"),
        "ShareOfProfitLossOfAssociates": ("share_of_profit_loss_of_associates", "INR"),
        "TaxExpense": ("tax_expense", "INR"),
        "UnAllocableAssets": ("un_allocable_assets", "INR"),
        "UnAllocableLiabilities": ("un_allocable_liabilities", "INR"),
    },
    NS_CAPMKT_2020: {
        "AdministrationExpenses": ("administration_expenses", "INR"),
        "AdvancesAndOtherAssets": ("advances_and_other_assets", "INR"),
        "AdvertisementAndPublicity": ("advertisement_and_publicity", "INR"),
        "AllocationOfBonusToPolicyholders": ("allocation_of_bonus_to_policyholders", "INR"),
        "ApplicationOfFunds": ("application_of_funds", "INR"),
        "Assets": ("assets", "INR"),
        "AssetsHeldToCoverLinkLiabilities": ("assets_held_to_cover_link_liabilities", "INR"),
        "AssetsHeldToCoverLinkedLiabilities": ("assets_held_to_cover_linked_liabilities", "INR"),
        "BasicAndDilutedEPSAfterExtraordinaryItemsNetOfTaxExpenseForThePeriodNotToBeAnnualized": ("basic_and_diluted_eps_after_extraordinary_items_net_of_tax_expense_for_the_period_not_to_be_annualized", "INR/share"),
        "BasicAndDilutedEPSBeforeExtraordinaryItemsNetOfTaxExpenseForThePeriodNotToBeAnnualized": ("basic_and_diluted_eps_before_extraordinary_items_net_of_tax_expense_for_the_period_not_to_be_annualized", "INR/share"),
        "BenefitsPaidNet": ("benefits_paid_net", "INR"),
        "Borrowings": ("borrowings", "INR"),
        "CashAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": ("cash_advances_and_loans_made_to_other_parties_classified_as_investing_activities", "INR"),
        "CashAndBankBalances": ("cash_and_bank_balances", "INR"),
        "CashAndCashEquivalentsCashFlowStatement": ("cash_and_cash_equivalents_cash_flow_statement", "INR"),
        "CashFlowsFromLosingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": ("cash_flows_from_losing_control_of_subsidiaries_or_other_businesses_classified_as_investing_activities", "INR"),
        "CashFlowsFromUsedInFinancingActivities": ("cash_flows_from_used_in_financing_activities", "INR"),
        "CashFlowsFromUsedInInvestingActivities": ("cash_flows_from_used_in_investing_activities", "INR"),
        "CashFlowsFromUsedInOperatingActivities": ("cash_flows_from_used_in_operating_activities", "INR"),
        "CashFlowsFromUsedInOperations": ("cash_flows_from_used_in_operations", "INR"),
        "CashFlowsUsedInObtainingControlOfSubsidiariesOrOtherBusinessesClassifiedAsInvestingActivities": ("cash_flows_used_in_obtaining_control_of_subsidiaries_or_other_businesses_classified_as_investing_activities", "INR"),
        "CashPaymentsForFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": ("cash_payments_for_future_contracts_forward_contracts_option_contracts_and_swap_contracts_classified_as_investing_activities", "INR"),
        "CashReceiptsFromFutureContractsForwardContractsOptionContractsAndSwapContractsClassifiedAsInvestingActivities": ("cash_receipts_from_future_contracts_forward_contracts_option_contracts_and_swap_contracts_classified_as_investing_activities", "INR"),
        "CashReceiptsFromRepaymentOfAdvancesAndLoansMadeToOtherPartiesClassifiedAsInvestingActivities": ("cash_receipts_from_repayment_of_advances_and_loans_made_to_other_parties_classified_as_investing_activities", "INR"),
        "ChangeInActuarialLiability": ("change_in_actuarial_liability", "INR"),
        "ChangeInFairvalueAccount": ("change_in_fairvalue_account", "INR"),
        "ChangeInOutstandingClaims": ("change_in_outstanding_claims", "INR"),
        "ClaimsPaid": ("claims_paid", "INR"),
        "CombinedRatio": ("combined_ratio", "pure"),
        "Commission": ("commission", "INR"),
        "CommissionFirstYearPremium": ("commission_first_year_premium", "INR"),
        "CommissionRenewalPremium": ("commission_renewal_premium", "INR"),
        "CommissionSinglePremium": ("commission_single_premium", "INR"),
        "CommissionsAndBrokerageNet": ("commissions_and_brokerage_net", "INR"),
        "ConservationRatio": ("conservation_ratio", "pure"),
        "ContigentLiabilities": ("contigent_liabilities", "INR"),
        "CreditDebitFairValueChangeAccount": ("credit_debit_fair_value_change_account", "INR"),
        "CreditDebitFairValueChangeAccountFundsForDiscontinuedPolicies": ("credit_debit_fair_value_change_account_funds_for_discontinued_policies", "INR"),
        "CreditDebitFairValueChangeAccountPolicyholdersFunds": ("credit_debit_fair_value_change_account_policyholders_funds", "INR"),
        "CurrentAssets": ("current_assets", "INR"),
        "CurrentLiabilities": ("current_liabilities", "INR"),
        "CurrentLiabilitiesAndProvisions": ("current_liabilities_and_provisions", "INR"),
        "CurrentTax": ("current_tax", "INR"),
        "CurrentTaxes": ("current_taxes", "INR"),
        "DebitBalanceInProfitAndLossAccountShareholdersAccount": ("debit_balance_in_profit_and_loss_account_shareholders_account", "INR"),
        "DeferredTaxAsset": ("deferred_tax_asset", "INR"),
        "DefferedTax": ("deffered_tax", "INR"),
        "DefferedTaxes": ("deffered_taxes", "INR"),
        "DiscontinuedOnAccountOfNonPaymentOfPremium": ("discontinued_on_account_of_non_payment_of_premium", "INR"),
        "DividendsPaidClassifiedAsFinancingActivities": ("dividends_paid_classified_as_financing_activities", "INR"),
        "DividendsReceivedClassifiedAsInvestingActivities": ("dividends_received_classified_as_investing_activities", "INR"),
        "DividendsReceivedClassifiedAsOperatingActivities": ("dividends_received_classified_as_operating_activities", "INR"),
        "EffectOfExchangeRateChangesOnCashAndCashEquivalents": ("effect_of_exchange_rate_changes_on_cash_and_cash_equivalents", "INR"),
        "EmployeesRemunerationAndWelfareExpenses": ("employees_remuneration_and_welfare_expenses", "INR"),
        "Expenses": ("expenses", "INR"),
        "ExpensesOfManagement": ("expenses_of_management", "INR"),
        "ExpensesOfManagementRatio": ("expenses_of_management_ratio", "pure"),
        "ExpensesOtherThanThoseRelatedToInsuranceBusiness": ("expenses_other_than_those_related_to_insurance_business", "INR"),
        "ExtraordinaryItems": ("extraordinary_items", "INR"),
        "ExtraordinaryItemsNetOfTaxExpenses": ("extraordinary_items_net_of_tax_expenses", "INR"),
        "FairValueChangeAccountAndRevaluationReserve": ("fair_value_change_account_and_revaluation_reserve", "INR"),
        "FairValueChangeAccountAndRevaluationReserveShareholders": ("fair_value_change_account_and_revaluation_reserve_shareholders", "INR"),
        "FinalDividend": ("final_dividend", "INR"),
        "FixedAssets": ("fixed_assets", "INR"),
        "FundsForFutureAppropriation": ("funds_for_future_appropriation", "INR"),
        "FundsForFutureAppropriations": ("funds_for_future_appropriations", "INR"),
        "GoodsAndServiceTaxChargeOnLinkedCharges": ("goods_and_service_tax_charge_on_linked_charges", "INR"),
        "GrossNPAsPolicyholdersFund": ("gross_npas_policyholders_fund", "INR"),
        "GrossNPAsShareholdersFund": ("gross_npas_shareholders_fund", "INR"),
        "GrossPremiumIncome": ("gross_premium_income", "INR"),
        "GrossPremiumsWritten": ("gross_premiums_written", "INR"),
        "Income": ("income", "INR"),
        "IncomeFirstYearPremium": ("income_first_year_premium", "INR"),
        "IncomeFromInvestmentsNet": ("income_from_investments_net", "INR"),
        "IncomeInShareholdersAccount": ("income_in_shareholders_account", "INR"),
        "IncomeRenewalPremium": ("income_renewal_premium", "INR"),
        "IncomeSinglePremium": ("income_single_premium", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsFinancingActivities": ("income_taxes_paid_refund_classified_as_financing_activities", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsInvestingActivities": ("income_taxes_paid_refund_classified_as_investing_activities", "INR"),
        "IncomeTaxesPaidRefundClassifiedAsOperatingActivities": ("income_taxes_paid_refund_classified_as_operating_activities", "INR"),
        "IncomeUnderShareholdersAccount": ("income_under_shareholders_account", "INR"),
        "IncreaseDecreaseInCashAndCashEquivalents": ("increase_decrease_in_cash_and_cash_equivalents", "INR"),
        "IncreaseDecreaseInCashAndCashEquivalentsBeforeEffectOfExchangeRateChanges": ("increase_decrease_in_cash_and_cash_equivalents_before_effect_of_exchange_rate_changes", "INR"),
        "IncurredClaimRatio": ("incurred_claim_ratio", "pure"),
        "IncurredClaims": ("incurred_claims", "INR"),
        "InsuranceReserve": ("insurance_reserve", "INR"),
        "InterestPaidClassifiedAsFinancingActivities": ("interest_paid_classified_as_financing_activities", "INR"),
        "InterestPaidClassifiedAsOperatingActivities": ("interest_paid_classified_as_operating_activities", "INR"),
        "InterestReceivedClassifiedAsInvestingActivities": ("interest_received_classified_as_investing_activities", "INR"),
        "InterestReceivedClassifiedAsOperatingActivities": ("interest_received_classified_as_operating_activities", "INR"),
        "InterimBonusPaid": ("interim_bonus_paid", "INR"),
        "InterimDividend": ("interim_dividend", "INR"),
        "InvestmentIncome": ("investment_income", "INR"),
        "Investments": ("investments", "INR"),
        "InvestmentsPolicyholders": ("investments_policyholders", "INR"),
        "InvestmentsShareholders": ("investments_shareholders", "INR"),
        "LinkedLiabilities": ("linked_liabilities", "INR"),
        "LinkedNonParticipatingPolicyholdersFundGrossNPAs": ("linked_non_participating_policyholders_fund_gross_npas", "pure"),
        "LinkedNonParticipatingPolicyholdersFundNetNPAs": ("linked_non_participating_policyholders_fund_net_npas", "pure"),
        "LinkedNonParticipatingPolicyholdersFundPercentageOfGrossNPAs": ("linked_non_participating_policyholders_fund_percentage_of_gross_npas", "pure"),
        "LinkedNonParticipatingPolicyholdersFundPercentageOfNetNPAs": ("linked_non_participating_policyholders_fund_percentage_of_net_npas", "pure"),
        "LinkedNonParticipatingPolicyholdersFundWithUnrealisedGains": ("linked_non_participating_policyholders_fund_with_unrealised_gains", "pure"),
        "LinkedNonParticipatingPolicyholdersFundWithoutUnrealisedGains": ("linked_non_participating_policyholders_fund_without_unrealised_gains", "pure"),
        "LinkedParticipatingPolicyholdersFundGrossNPAs": ("linked_participating_policyholders_fund_gross_npas", "pure"),
        "LinkedParticipatingPolicyholdersFundNetNPAs": ("linked_participating_policyholders_fund_net_npas", "pure"),
        "LinkedParticipatingPolicyholdersFundPercentageOfGrossNPAs": ("linked_participating_policyholders_fund_percentage_of_gross_npas", "pure"),
        "LinkedParticipatingPolicyholdersFundPercentageOfNetNPAs": ("linked_participating_policyholders_fund_percentage_of_net_npas", "pure"),
        "LinkedParticipatingPolicyholdersFundWithUnrealisedGains": ("linked_participating_policyholders_fund_with_unrealised_gains", "pure"),
        "LinkedParticipatingPolicyholdersFundWithoutUnrealisedGains": ("linked_participating_policyholders_fund_without_unrealised_gains", "pure"),
        "Loans": ("loans", "INR"),
        "MiscellaneousExpenditureToTheExtentNotWrittenOffOrAdjusted": ("miscellaneous_expenditure_to_the_extent_not_written_off_or_adjusted", "INR"),
        "NetCommission": ("net_commission", "INR"),
        "NetCurrentAssets": ("net_current_assets", "INR"),
        "NetNPAsPolicyholdersFund": ("net_npas_policyholders_fund", "INR"),
        "NetNPAsShareholdersFund": ("net_npas_shareholders_fund", "INR"),
        "NetPremiumIncome": ("net_premium_income", "INR"),
        "NetPremiumWritten": ("net_premium_written", "INR"),
        "NetRetentionRatio": ("net_retention_ratio", "pure"),
        "NetSurplusDeficit": ("net_surplus_deficit", "INR"),
        "NoOfInvestorComplaintsDisposedOffDuringThePeriod": ("no_of_investor_complaints_disposed_off_during_the_period", "pure"),
        "NoOfInvestorComplaintsDuringThePeriod": ("no_of_investor_complaints_during_the_period", "pure"),
        "NoOfInvestorComplaintsPendingAtTheBeginningOfThePeriod": ("no_of_investor_complaints_pending_at_the_beginning_of_the_period", "pure"),
        "NoOfInvestorComplaintsRemainingUnresolvedAtTheEndOfThePeriod": ("no_of_investor_complaints_remaining_unresolved_at_the_end_of_the_period", "pure"),
        "NonLinkedNonParticipatingPolicyholdersFundGrossNPAs": ("non_linked_non_participating_policyholders_fund_gross_npas", "pure"),
        "NonLinkedNonParticipatingPolicyholdersFundNetNPAs": ("non_linked_non_participating_policyholders_fund_net_npas", "pure"),
        "NonLinkedNonParticipatingPolicyholdersFundPercentageOfGrossNPAs": ("non_linked_non_participating_policyholders_fund_percentage_of_gross_npas", "pure"),
        "NonLinkedNonParticipatingPolicyholdersFundPercentageOfNetNPAs": ("non_linked_non_participating_policyholders_fund_percentage_of_net_npas", "pure"),
        "NonLinkedNonParticipatingPolicyholdersFundWithUnrealisedGains": ("non_linked_non_participating_policyholders_fund_with_unrealised_gains", "pure"),
        "NonLinkedNonParticipatingPolicyholdersFundWithoutUnrealisedGains": ("non_linked_non_participating_policyholders_fund_without_unrealised_gains", "pure"),
        "NonLinkedParticipatingPolicyholdersFundGrossNPAs": ("non_linked_participating_policyholders_fund_gross_npas", "pure"),
        "NonLinkedParticipatingPolicyholdersFundNetNPAs": ("non_linked_participating_policyholders_fund_net_npas", "pure"),
        "NonLinkedParticipatingPolicyholdersFundPercentageOfGrossNPAs": ("non_linked_participating_policyholders_fund_percentage_of_gross_npas", "pure"),
        "NonLinkedParticipatingPolicyholdersFundPercentageOfNetNPAs": ("non_linked_participating_policyholders_fund_percentage_of_net_npas", "pure"),
        "NonLinkedParticipatingPolicyholdersFundWithUnrealisedGains": ("non_linked_participating_policyholders_fund_with_unrealised_gains", "pure"),
        "NonLinkedParticipatingPolicyholdersFundWithoutUnrealisedGains": ("non_linked_participating_policyholders_fund_without_unrealised_gains", "pure"),
        "NonOperatingExpense": ("non_operating_expense", "INR"),
        "NonOperatingExpensesOtherThanThoseRelatedToInsuranceBusiness": ("non_operating_expenses_other_than_those_related_to_insurance_business", "INR"),
        "NonOperatingProvisionsForDiminutionInValueOfInvestments": ("non_operating_provisions_for_diminution_in_value_of_investments", "INR"),
        "NonOperatingProvisionsForDoubtfulDebtsIncludingBadDebtsWrittenOff": ("non_operating_provisions_for_doubtful_debts_including_bad_debts_written_off", "INR"),
        "NumberOfShares": ("number_of_shares", "shares"),
        "OpeningBalanceAndApproproationsFromPATNet": ("opening_balance_and_approproations_from_pat_net", "INR"),
        "OperatingExpenses": ("operating_expenses", "INR"),
        "OperatingExpensesRelatedToInsuranceBusiness": ("operating_expenses_related_to_insurance_business", "INR"),
        "OperatingIncome": ("operating_income", "INR"),
        "OperatingProfitOrLoss": ("operating_profit_or_loss", "INR"),
        "OtherAssetsNetOfCurrentLiabilitiesAndProvisions": ("other_assets_net_of_current_liabilities_and_provisions", "INR"),
        "OtherCashPaymentsFromOperatingActivities": ("other_cash_payments_from_operating_activities", "INR"),
        "OtherCashPaymentsToAcquireEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": ("other_cash_payments_to_acquire_equity_or_debt_instruments_of_other_entities_classified_as_investing_activities", "INR"),
        "OtherCashPaymentsToAcquireInterestsInJointVenturesClassifiedAsInvestingActivities": ("other_cash_payments_to_acquire_interests_in_joint_ventures_classified_as_investing_activities", "INR"),
        "OtherCashReceiptsFromOperatingActivities": ("other_cash_receipts_from_operating_activities", "INR"),
        "OtherCashReceiptsFromSalesOfEquityOrDebtInstrumentsOfOtherEntitiesClassifiedAsInvestingActivities": ("other_cash_receipts_from_sales_of_equity_or_debt_instruments_of_other_entities_classified_as_investing_activities", "INR"),
        "OtherCashReceiptsFromSalesOfInterestsInJointVenturesClassifiedAsInvestingActivities": ("other_cash_receipts_from_sales_of_interests_in_joint_ventures_classified_as_investing_activities", "INR"),
        "OtherIncome": ("other_income", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsFinancingActivities": ("other_inflows_outflows_of_cash_classified_as_financing_activities", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsInvestingActivities": ("other_inflows_outflows_of_cash_classified_as_investing_activities", "INR"),
        "OtherInflowsOutflowsOfCashClassifiedAsOperatingActivities": ("other_inflows_outflows_of_cash_classified_as_operating_activities", "INR"),
        "OtherOperatingExpenses": ("other_operating_expenses", "INR"),
        "OthersDiscontinuance": ("others_discontinuance", "INR"),
        "PaidUpEquityCapital": ("paid_up_equity_capital", "INR"),
        "PaidUpEquityShareCapital": ("paid_up_equity_share_capital", "INR"),
        "PaymentsForPremiumsAndClaimsAnnuitiesAndOtherPolicyBenefits": ("payments_for_premiums_and_claims_annuities_and_other_policy_benefits", "INR"),
        "PaymentsFromChangesInOwnershipInterestsInSubsidiariesThatDoNotResultInLossOfControl": ("payments_from_changes_in_ownership_interests_in_subsidiaries_that_do_not_result_in_loss_of_control", "INR"),
        "PaymentsFromContractsHeldForDealingOrTradingPurpose": ("payments_from_contracts_held_for_dealing_or_trading_purpose", "INR"),
        "PaymentsOfFinanceLeaseLiabilitiesClassifiedAsFinancingActivities": ("payments_of_finance_lease_liabilities_classified_as_financing_activities", "INR"),
        "PaymentsOfLeaseLiabilitiesClassifiedAsFinancingActivities": ("payments_of_lease_liabilities_classified_as_financing_activities", "INR"),
        "PaymentsOfOtherEquityInstruments": ("payments_of_other_equity_instruments", "INR"),
        "PaymentsToAcquireOrRedeemEntitysShares": ("payments_to_acquire_or_redeem_entitys_shares", "INR"),
        "PaymentsToAndOnBehalfOfEmployees": ("payments_to_and_on_behalf_of_employees", "INR"),
        "PaymentsToManufactureOrAcquireAssetsHeldForRentalToOthersAndSubsequentlyHeldForSale": ("payments_to_manufacture_or_acquire_assets_held_for_rental_to_others_and_subsequently_held_for_sale", "INR"),
        "PaymentsToSuppliersForGoodsAndServices": ("payments_to_suppliers_for_goods_and_services", "INR"),
        "PercentageOfGovernmentHolding": ("percentage_of_government_holding", "pure"),
        "PercentageOfGrossNPAsPolicyholdersFund": ("percentage_of_gross_npas_policyholders_fund", "pure"),
        "PercentageOfGrossNPAsShareholdersFund": ("percentage_of_gross_npas_shareholders_fund", "pure"),
        "PercentageOfNetNPAsPolicyholdersFund": ("percentage_of_net_npas_policyholders_fund", "pure"),
        "PercentageOfNetNPAsShareholdersFund": ("percentage_of_net_npas_shareholders_fund", "pure"),
        "PercentageOfShareholding": ("percentage_of_shareholding", "pure"),
        "PercentageOfSharesHeldByGovernmentOfIndiaInCaseOfPublicSectorInsuranceCompanies": ("percentage_of_shares_held_by_government_of_india_in_case_of_public_sector_insurance_companies", "pure"),
        "PersistencyRatio13ThMonth": ("persistency_ratio_13th_month", "pure"),
        "PersistencyRatio25ThMonth": ("persistency_ratio_25th_month", "pure"),
        "PersistencyRatio37ThMonth": ("persistency_ratio_37th_month", "pure"),
        "PersistencyRatio49ThMonth": ("persistency_ratio_49th_month", "pure"),
        "PolicyLiabilities": ("policy_liabilities", "INR"),
        "PolicyholdersAccountOtherIncome": ("policyholders_account_other_income", "INR"),
        "PolicyholdersFund": ("policyholders_fund", "INR"),
        "PolicyholdersFundExcludingLinkedAssets": ("policyholders_fund_excluding_linked_assets", "INR"),
        "PolicyholdersFunds": ("policyholders_funds", "INR"),
        "PolicyholdersLiabilitiesToShareholdersFund": ("policyholders_liabilities_to_shareholders_fund", "INR"),
        "PremiumDeficiency": ("premium_deficiency", "INR"),
        "PremiumEarned": ("premium_earned", "INR"),
        "ProceedsFromBiologicalAssetsOtherThanBearerPlantsClassifiedAsInvestingActivities": ("proceeds_from_biological_assets_other_than_bearer_plants_classified_as_investing_activities", "INR"),
        "ProceedsFromBorrowingsClassifiedAsFinancingActivities": ("proceeds_from_borrowings_classified_as_financing_activities", "INR"),
        "ProceedsFromChangesInOwnershipInterestsInSubsidiariesThatDoNotResultInLossOfControl": ("proceeds_from_changes_in_ownership_interests_in_subsidiaries_that_do_not_result_in_loss_of_control", "INR"),
        "ProceedsFromExerciseOfStockOptions": ("proceeds_from_exercise_of_stock_options", "INR"),
        "ProceedsFromGovernmentGrantsClassifiedAsInvestingActivities": ("proceeds_from_government_grants_classified_as_investing_activities", "INR"),
        "ProceedsFromIssuingDebenturesNotesBondsEtc": ("proceeds_from_issuing_debentures_notes_bonds_etc", "INR"),
        "ProceedsFromIssuingOtherEquityInstruments": ("proceeds_from_issuing_other_equity_instruments", "INR"),
        "ProceedsFromIssuingSharesClassifiedAsFinancingActivities": ("proceeds_from_issuing_shares_classified_as_financing_activities", "INR"),
        "ProceedsFromSalesOfGoodwillClassifiedAsInvestingActivities": ("proceeds_from_sales_of_goodwill_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfIntangibleAssetsClassifiedAsInvestingActivities": ("proceeds_from_sales_of_intangible_assets_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfInvestmentPropertyClassifiedAsInvestingActivities": ("proceeds_from_sales_of_investment_property_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfOtherLongTermAssetsClassifiedAsInvestingActivities": ("proceeds_from_sales_of_other_long_term_assets_classified_as_investing_activities", "INR"),
        "ProceedsFromSalesOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities": ("proceeds_from_sales_of_property_plant_and_equipment_classified_as_investing_activities", "INR"),
        "ProfitLossAfterTax": ("profit_loss_after_tax", "INR"),
        "ProfitLossAfterTaxAndExtraordinaryItems": ("profit_loss_after_tax_and_extraordinary_items", "INR"),
        "ProfitLossAfterTaxBeforeExtraordinaryItems": ("profit_loss_after_tax_before_extraordinary_items", "INR"),
        "ProfitLossBeforeTax": ("profit_loss_before_tax", "INR"),
        "ProfitLossCarriedToBalanceSheet": ("profit_loss_carried_to_balance_sheet", "INR"),
        "ProfitOrLossBeforeExtraordinaryItems": ("profit_or_loss_before_extraordinary_items", "INR"),
        "ProfitOrLossBeforeTax": ("profit_or_loss_before_tax", "INR"),
        "ProvisionForLinkedLiabilities": ("provision_for_linked_liabilities", "INR"),
        "ProvisionForTax": ("provision_for_tax", "INR"),
        "Provisions": ("provisions", "INR"),
        "ProvisionsForDiminutionInValueOfInvestments": ("provisions_for_diminution_in_value_of_investments", "INR"),
        "ProvisionsForDoubtfulDebtsIncludingBadDebtsWrittenOff": ("provisions_for_doubtful_debts_including_bad_debts_written_off", "INR"),
        "ProvisionsForDoubtfulDebtsIncludingWriteOff": ("provisions_for_doubtful_debts_including_write_off", "INR"),
        "ProvisionsForTax": ("provisions_for_tax", "INR"),
        "ProvisionsForTaxes": ("provisions_for_taxes", "INR"),
        "PurchaseOfBiologicalAssetsOtherThanBearerPlantsClassifiedAsInvestingActivities": ("purchase_of_biological_assets_other_than_bearer_plants_classified_as_investing_activities", "INR"),
        "PurchaseOfGoodwillClassifiedAsInvestingActivities": ("purchase_of_goodwill_classified_as_investing_activities", "INR"),
        "PurchaseOfIntangibleAssetsClassifiedAsInvestingActivities": ("purchase_of_intangible_assets_classified_as_investing_activities", "INR"),
        "PurchaseOfInvestmentPropertyClassifiedAsInvestingActivities": ("purchase_of_investment_property_classified_as_investing_activities", "INR"),
        "PurchaseOfOtherLongTermAssetsClassifiedAsInvestingActivities": ("purchase_of_other_long_term_assets_classified_as_investing_activities", "INR"),
        "PurchaseOfPropertyPlantAndEquipmentClassifiedAsInvestingActivities": ("purchase_of_property_plant_and_equipment_classified_as_investing_activities", "INR"),
        "ReceiptsFromContractsHeldForDealingOrTradingPurpose": ("receipts_from_contracts_held_for_dealing_or_trading_purpose", "INR"),
        "ReceiptsFromPremiumsAndClaimsAnnuitiesAndOtherPolicyBenefits": ("receipts_from_premiums_and_claims_annuities_and_other_policy_benefits", "INR"),
        "ReceiptsFromRentsAndSubsequentSalesOfAssetsHeldForRentalToOthersAndSubsequentlyHeldForSale": ("receipts_from_rents_and_subsequent_sales_of_assets_held_for_rental_to_others_and_subsequently_held_for_sale", "INR"),
        "ReceiptsFromRoyaltiesFeesCommissionsAndOtherRevenue": ("receipts_from_royalties_fees_commissions_and_other_revenue", "INR"),
        "ReceiptsFromSalesOfGoodsAndRenderingOfServices": ("receipts_from_sales_of_goods_and_rendering_of_services", "INR"),
        "RepaymentsOfBorrowingsClassifiedAsFinancingActivities": ("repayments_of_borrowings_classified_as_financing_activities", "INR"),
        "ReserveAndSurplus": ("reserve_and_surplus", "INR"),
        "ReservesAndSurplus": ("reserves_and_surplus", "INR"),
        "RevaluationReserveInvestmentProperty": ("revaluation_reserve_investment_property", "INR"),
        "ShareApplicationMoneyReceivedPendingAllotmentOfShares": ("share_application_money_received_pending_allotment_of_shares", "INR"),
        "ShareCapital": ("share_capital", "INR"),
        "ShareholderFund": ("shareholder_fund", "INR"),
        "ShareholdersAccountExpenses": ("shareholders_account_expenses", "INR"),
        "ShareholdersAccountIncome": ("shareholders_account_income", "INR"),
        "ShareholdersAccountIncomeFromInvestments": ("shareholders_account_income_from_investments", "INR"),
        "ShareholdersAccountOtherIncome": ("shareholders_account_other_income", "INR"),
        "ShareholdersAccountProvisionsForDiminutionInValueOfInvestments": ("shareholders_account_provisions_for_diminution_in_value_of_investments", "INR"),
        "ShareholdersAccountTransferFromPolicyholdersFund": ("shareholders_account_transfer_from_policyholders_fund", "INR"),
        "ShareholdersFundWithUnrealisedGains": ("shareholders_fund_with_unrealised_gains", "INR"),
        "ShareholdersFundWithoutUnrealisedGains": ("shareholders_fund_without_unrealised_gains", "INR"),
        "SolvencyRatio": ("solvency_ratio", "pure"),
        "SourcesOfFunds": ("sources_of_funds", "INR"),
        "SurplusDeficit": ("surplus_deficit", "INR"),
        "SurplusShownInTheRevenueAccount": ("surplus_shown_in_the_revenue_account", "INR"),
        "TerminalBonusPaid": ("terminal_bonus_paid", "INR"),
        "TransferFromPolicyholdersAccount": ("transfer_from_policyholders_account", "INR"),
        "TransferOfFundsFromShareholdersAccount": ("transfer_of_funds_from_shareholders_account", "INR"),
        "TransferOfFundsToPolicyholdersAccount": ("transfer_of_funds_to_policyholders_account", "INR"),
        "TransferToProfitAndLossAccount": ("transfer_to_profit_and_loss_account", "INR"),
        "TransferToReserves": ("transfer_to_reserves", "INR"),
        "TransferredToShareholdersAccount": ("transferred_to_shareholders_account", "INR"),
        "UnderwritingProfitOrLoss": ("underwriting_profit_or_loss", "INR"),
        "WithUnrealisedGains": ("with_unrealised_gains", "INR"),
        "WithoutUnrealizedGains": ("without_unrealized_gains", "INR"),
    },
}
